// <auto-generated />
using System;
using Maquinitas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maquinitas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818044246_RenameCorteMaquinaEmpleadoToRegistradoPor")]
    partial class RenameCorteMaquinaEmpleadoToRegistradoPor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maquinitas.Domain.Entities.Auditoria.AuditoriaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Entidad", "EntidadId");

                    b.ToTable("AuditoriaEventos");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Averias.EvidenciaAveria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReporteAveriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReporteAveriaId");

                    b.ToTable("EvidenciasAveria");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Averias.ReporteAveria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoAlReportar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("LocalId");

                    b.HasIndex("MaquinaId");

                    b.ToTable("ReportesAveria");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemanaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalReportado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("SemanaId");

                    b.HasIndex("LocalId", "EmpleadoId", "Fecha");

                    b.ToTable("CierresDiarios");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreDiarioDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CierreDiarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Concepto")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DenominacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PremioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CierreDiarioId");

                    b.HasIndex("DenominacionId");

                    b.HasIndex("PremioId");

                    b.ToTable("CierreDiarioDetalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ConfirmadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoDiferencia")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemanaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalReportado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmadoPorUsuarioId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("LocalId");

                    b.HasIndex("SemanaId")
                        .IsUnique();

                    b.ToTable("CierresSemanales");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreSemanalDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CierreSemanalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Concepto")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DenominacionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPremioPuesto")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PremioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CierreSemanalId");

                    b.HasIndex("DenominacionId");

                    b.HasIndex("PremioId");

                    b.ToTable("CierreSemanalDetalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemanaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("LocalId");

                    b.HasIndex("SemanaId");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.CuentaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DenominacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PremioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("DenominacionId");

                    b.HasIndex("PremioId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.ToTable("CuentaDetalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.CuentaModificacionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NotificacionEnviada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentaModificacionLogs");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.Denominacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ValorPorBolsa")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Denominaciones");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.CategoriaGasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasGasto");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GastoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GastoId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaGastoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CierreDiarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("CierreDiarioId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("LocalId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PropietarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PropietarioId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Identity.UsuarioLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId", "LocalId")
                        .IsUnique();

                    b.ToTable("UsuarioLocales");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Locales.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Locales");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.CorteMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("MaquinaId", "Fecha");

                    b.ToTable("CortesMaquina");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.CorteMaquinaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorteMaquinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DenominacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PremioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CorteMaquinaId");

                    b.HasIndex("DenominacionId");

                    b.HasIndex("PremioId");

                    b.ToTable("CorteMaquinaDetalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.HistorialEstadoMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEstadosMaquina");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.Maquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("text");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoMaquinaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.Propietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.TipoMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposMaquina");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Notificaciones.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId", "Leida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.InventarioPremio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InventariosPremios");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.InventarioPremioDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadConfigurada")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEncontrada")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventarioPremioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PremioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventarioPremioId");

                    b.HasIndex("PremioId");

                    b.ToTable("InventarioPremioDetalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.MaquinaPremio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadAsignada")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PremioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PremioId");

                    b.HasIndex("MaquinaId", "PremioId")
                        .IsUnique();

                    b.ToTable("MaquinaPremios");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.Premio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Denominacion")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Semanas.Semana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalId", "Numero")
                        .IsUnique();

                    b.ToTable("Semanas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Averias.EvidenciaAveria", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Averias.ReporteAveria", "ReporteAveria")
                        .WithMany("Evidencias")
                        .HasForeignKey("ReporteAveriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReporteAveria");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Averias.ReporteAveria", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Maquina", "Maquina")
                        .WithMany("ReportesAveria")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Local");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreDiario", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Semanas.Semana", "Semana")
                        .WithMany()
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Local");

                    b.Navigation("Semana");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreDiarioDetalle", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Cierres.CierreDiario", "CierreDiario")
                        .WithMany("Detalles")
                        .HasForeignKey("CierreDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Cuentas.Denominacion", "Denominacion")
                        .WithMany()
                        .HasForeignKey("DenominacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Premios.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CierreDiario");

                    b.Navigation("Denominacion");

                    b.Navigation("Premio");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreSemanal", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "ConfirmadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ConfirmadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Semanas.Semana", "Semana")
                        .WithMany()
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmadoPorUsuario");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Local");

                    b.Navigation("Semana");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreSemanalDetalle", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Cierres.CierreSemanal", "CierreSemanal")
                        .WithMany("Detalles")
                        .HasForeignKey("CierreSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Cuentas.Denominacion", "Denominacion")
                        .WithMany()
                        .HasForeignKey("DenominacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Premios.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CierreSemanal");

                    b.Navigation("Denominacion");

                    b.Navigation("Premio");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.Cuenta", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany("Cuentas")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Semanas.Semana", "Semana")
                        .WithMany()
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Local");

                    b.Navigation("Semana");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.CuentaDetalle", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Cuentas.Cuenta", "Cuenta")
                        .WithMany("Detalles")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Cuentas.Denominacion", "Denominacion")
                        .WithMany()
                        .HasForeignKey("DenominacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Premios.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "RegistradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Denominacion");

                    b.Navigation("Premio");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.CuentaModificacionLog", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Cuentas.Cuenta", "Cuenta")
                        .WithMany("Modificaciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.Evidencia", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Gastos.Gasto", "Gasto")
                        .WithMany("Evidencias")
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gasto");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.Gasto", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Gastos.CategoriaGasto", "CategoriaGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaGastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Cierres.CierreDiario", "CierreDiario")
                        .WithMany("Gastos")
                        .HasForeignKey("CierreDiarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaGasto");

                    b.Navigation("CierreDiario");

                    b.Navigation("Empleado");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Identity.UsuarioLocal", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany("UsuarioLocales")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Usuario")
                        .WithMany("UsuarioLocales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.CorteMaquina", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Maquina");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.CorteMaquinaDetalle", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.CorteMaquina", "CorteMaquina")
                        .WithMany("Detalles")
                        .HasForeignKey("CorteMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Cuentas.Denominacion", "Denominacion")
                        .WithMany()
                        .HasForeignKey("DenominacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Premios.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorteMaquina");

                    b.Navigation("Denominacion");

                    b.Navigation("Premio");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.HistorialEstadoMaquina", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Maquina", "Maquina")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.Maquina", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany("Maquinas")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Propietario", "Propietario")
                        .WithMany("Maquinas")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.TipoMaquina", "TipoMaquina")
                        .WithMany("Maquinas")
                        .HasForeignKey("TipoMaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Propietario");

                    b.Navigation("TipoMaquina");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Notificaciones.Notificacion", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.InventarioPremio", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Maquina", "Maquina")
                        .WithMany("InventariosPremios")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.InventarioPremioDetalle", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Premios.InventarioPremio", "InventarioPremio")
                        .WithMany("Detalles")
                        .HasForeignKey("InventarioPremioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Premios.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventarioPremio");

                    b.Navigation("Premio");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.MaquinaPremio", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Maquinas.Maquina", "Maquina")
                        .WithMany("ConfiguracionPremios")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Premios.Premio", "Premio")
                        .WithMany("ConfiguracionesMaquina")
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Premio");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Semanas.Semana", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Locales.Local", "Local")
                        .WithMany("Semanas")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Maquinitas.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Averias.ReporteAveria", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreDiario", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cierres.CierreSemanal", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Cuentas.Cuenta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Modificaciones");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.CategoriaGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Gastos.Gasto", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UsuarioLocales");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Locales.Local", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("Maquinas");

                    b.Navigation("Semanas");

                    b.Navigation("UsuarioLocales");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.CorteMaquina", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.Maquina", b =>
                {
                    b.Navigation("ConfiguracionPremios");

                    b.Navigation("HistorialEstados");

                    b.Navigation("InventariosPremios");

                    b.Navigation("ReportesAveria");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.Propietario", b =>
                {
                    b.Navigation("Maquinas");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Maquinas.TipoMaquina", b =>
                {
                    b.Navigation("Maquinas");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.InventarioPremio", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Maquinitas.Domain.Entities.Premios.Premio", b =>
                {
                    b.Navigation("ConfiguracionesMaquina");
                });
#pragma warning restore 612, 618
        }
    }
}
